name: Electron Build and Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Electron application
        run: npm run distribute

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ github.token }}
        with:
          title: Release${{ github.run_number }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/*
